### ISSUE TITLE
Full-width characters in table disappear when scroll it

### ISSUE THREAD

**Issue by tmskst** [rivo/tview#212] opened 2018-12-21 14:29 UTC
1. Run this sample program.
2. Press <kbd>j</kbd> or <kbd>k</kbd>.
3. Full-width characters (such as "先生") disappear.
   (When resize the window, these characters appear again)

```
package main

import (
	"github.com/rivo/tview"
)

func main() {
	table := tview.NewTable()
	table.SetCellSimple(0, 0, "先生aa")
	table.SetCellSimple(1, 0, "博士bb")
	table.SetCellSimple(2, 0, "保存cc")
	application := tview.NewApplication()
	application.SetRoot(table, true)
	application.Run()
}
```

I found this problem on f93fbad8f8, Windows 10 + PowerShell

**Comment by rivo** [comment] 2018-12-25 17:58
I can't reproduce this. At least not after the latest commit. Could you please retest this with the latest commit and let me know if you still have that problem?

**Comment by tmskst** [comment] 2018-12-26 05:34
I retested with the latest commit (e432b27b03), but this problem still has occurred.
According to git bisect, 29458dad3ecc3dc44d699cf26c8e484385b46189 is the first bad commit
(I can't reproduce this problem on fed644683849886741e494ea1ada5c38b46705c1).

However, on fed644683849886741e494ea1ada5c38b46705c1, Full-width characters did not disappear after scrolling, but the characters shifted.
```
aa先生aa
bb博士bb
cc保存cc

↓  Press any key...

aa 先生a
bb 博士b
cc 保存c
```

**Comment by rivo** [comment] 2018-12-26 19:48
This appears to be a problem with `tcell`. I've opened an issue over there: https://github.com/gdamore/tcell/issues/250

**Comment by rivo** [comment] 2019-02-12 16:46
I'm closing this for now. I will get notified once gdamore/tcell#250 is solved and then I'll make sure it propagates to `tview`. (Although I believe nothing needs to be done here anyway.)

**Closed by rivo** 2019-02-12 16:46 UTC
