### ISSUE TITLE
SetBorder hides contents of List and TextView

### ISSUE THREAD

**Issue by VikiMaster2** [rivo/tview#141] opened 2018-07-21 14:12 UTC
When calling the SetBorder function on a List or a TextView (might be exhibited by other widgets too), no matter the argument, the contents of the targeted view get hidden and the view appears empty.

```
OS: Ubuntu 18.04
Shell: Bash 4.4.19
```

**Comment by rivo** [comment] 2018-07-27 15:42
I can't reproduce this. Can you send a short code snippet and a screenshot that illustrates this, please?

**Comment by VikiMaster2** [comment] 2018-07-27 16:47
Accourding to new observations, it appears that the issue is only present when the border is set using a chained `.SetBorder` function, which is most likely due to the output of the function. I appologize, if this is meant to function like this by design.

```
package main

import (
	"github.com/rivo/tview"
)

var app *tview.Application

func main() {
	app = tview.NewApplication()

	textView2 := tview.NewTextView().SetText("2222222")
	textView2.SetBorder(true)

	mainView :=
		tview.NewFlex().SetDirection(tview.FlexColumn).
			AddItem(tview.NewTextView().SetText("sdsddas").SetBorder(true), 0, 4, false). // ISSUE PRESENT
			AddItem(textView2, 30, 2, false)                                              // ISSUE ABSENT

	if err := app.SetRoot(mainView, true).Run(); err != nil {
		panic(err)
	}
}

func quit() {
	app.Stop()
}

```
![image](https://user-images.githubusercontent.com/7188510/43334198-5dfaad44-91d5-11e8-963d-b2ebc37ad87e.png)

**Comment by rivo** [comment] 2018-07-28 18:40
I understand. Well, `TextView` inherits `SetBorder()` from `Box` and because `SetBorder()` returns a `Box`, if you assign the result to a variable, you have a `Box` on your hand, not a `TextView`:

```go
iAmABox := tview.NewTextView().SetBorder(true)
```

This means that in your example, `tview` will call `Box`'s `Draw()`  function instead of `TextView`'s `Draw()` function so it ends up empty.

I don't know of any way of changing the function's return value without duplicating all functions in the child classes. So at this point, the only thing you can do is this:

```go
textView := tview.NewTextView()
textView.SetBorder(true)
```

**Comment by VikiMaster2** [comment] 2018-07-28 18:45
I understand. Sacrificing good code structure for a little convenience is never worth it. Thanks for taking your time. :+1:
Should I close this?

**Comment by rivo** [comment] 2018-08-04 09:51
I'll close it.

Not sure I'd say "never". I'm still wrestling with this decision because I tend to think that the convenience for the users (i.e. the developers who use `tview`) is more important. But it increases the boilerplate for every new primitive I introduce in the future, it duplicates a lot of code and documentation. And that's always a source for mistakes.

**Closed by rivo** 2018-08-04 09:51 UTC
