### ISSUE TITLE
[Bug] Selecting highlights with mouse doesn't work properly

### ISSUE THREAD

**Issue by normen** [rivo/tview#531] opened 2020-11-19 17:57 UTC
It seems a click on a TextView in a grid layout always selects the topmost visible region.

To reproduce:
- add a grid layout
- add a textview
- add enough paragraphs/regions with highlight IDs to the text view
- click on a region in the bottom of the text view
- the topmost row is selected

Maybe I missed something..?

Cheers,
Normen

**Comment by rivo** [comment] 2020-12-04 15:14
I tried this but could not reproduce it. Could you please paste a short program that illustrates this?

**Comment by normen** [comment] 2020-12-04 20:40
Hmm.. You're right, I tried and I couldn't, it worked as expected.. Must be something in my code then o_O Just wondering what - I don't do much different really..

**Comment by edlanda** [comment] 2021-03-04 18:20
It appears that having a region terminate at EOL triggers this.  To reproduce:

- Edit tview/demos/presentation/textview.go
- Insert a line to textView2 const, something like:     ["99"]foo[""]
- All regions following the insertion are unselectable and clicking on them selects region 99.
- Adding a character after the closing region tag causes correct behavior.

**Comment by rivo** [comment] 2021-04-27 07:09
Thanks, that was helpful. I believe the latest commit should fix this. If it doesn't, please reopen this issue.

**Closed** 2021-04-27 07:08 UTC
