### ISSUE TITLE
ANSI bright not respected when a color follows

### ISSUE THREAD

**Issue by tculp** [rivo/tview#495] opened 2020-09-03 17:31 UTC
`echo -e "\033[01;31mhi"` Produces bright/bold red text, but `echo -e "\033[01;31mhi" | go run ansi.go` does not show bright red text, just regular red text.

This is using the code provided on the ANSI wiki page: https://github.com/rivo/tview/wiki/ANSI.

Interestingly, faint text shows up as expected: `echo -e "\033[02;31mhi" | go run ansi.go`

**Comment by rivo** [comment] 2020-10-18 12:51
I can't reproduce this. Maybe this is because I'm using the new `tcell` version, to which `tview` was just upgraded. Or you're on a different terminal that's handling colours differently in different contexts. This is what it looks like for me (macOS, iTerm2):

![image](https://user-images.githubusercontent.com/480930/96367966-32f6f280-1151-11eb-84d9-738dbdc4a54d.png)

vs.

![image](https://user-images.githubusercontent.com/480930/96367973-3db18780-1151-11eb-9a72-6290b0a307f4.png)

Can you still reproduce your issue with the latest version? If so, please let me know your configuration (OS / which terminal).

**Comment by rivo** [comment] 2020-11-17 19:06
Since there was no further information provided, I'm closing this issue. If you still require information, please open a new issue and reference this one.

**Closed by rivo** 2020-11-17 19:06 UTC
