### ISSUE TITLE
Forms don't work in putty

### ISSUE THREAD

**Issue by rmasci** [rivo/tview#822] opened 2023-03-08 21:35 UTC
I developed on a mac, made a nice gui for my users -- then when I showed it to them it didn't work. They were using PuTTY, which is the main terminal program we use here for those that are stuck on windows. The user could click on things and it seemed to work but cut and paste didn't. Hoping someone knows how to fix this? :) thanks!

**Comment by digitallyserviced** [comment] 2023-03-12 04:56
I don’t believe cut will ever work but pasting may be something you can resolve. 

Look at gdamore/tcell issues for help since that is actually the paste handling.

**Comment by rivo** [comment] 2023-03-12 11:14
`tcell`'s pasting functionality will be added to `InputField` and `TextArea` once I have the time to do it.

Also, if you want to make copy&paste work for text areas on your specific system (e.g. Windows), see the text area documentation for instructions.

I'm closing this as this is not a bug but rather a feature request which I already know about. Also, "Forms don't work in putty" doesn't seem accurate. Your description indicates that forms do work in putty, just cut&paste is missing, which, as @digitallyserviced points out, is somewhat of a limitation of terminals in general.

**Closed by rivo** 2023-03-12 11:14 UTC
